### ISSUE TITLE
Make styling easier

### ISSUE THREAD

**Issue by danielgamage** [oakstudios/inline-svg#2]
Currently, we have a basic custom element (which `extends HTMLElement`) that wraps the inline SVG. This works, but adds a wrapper element that has its own intrinsic layout considerations.

### Suggest removal of box layout
This fix works now, but `display: contents` has some accessibility issues with interactive elements that may cause problems in some (albeit very specific) circumstances
```css
inline-svg {
  display: contents;
}
inline-svg svg {
  /* whatever layout styles are preferred */
}
```

### Make custom element extend `SVGElement`
Instead of extending HTMLElement, we could make this custom element a subclass of SVG, and when initializing the remote element, copy its `Element.attributes` to the root custom element before we append that element's `children` to the custom element.
